export const data = [
    {
      setName: "JavaScript Arrays",
      setNumber: 1,
      tech: "JavaScript",
      icon: "fab fa-js-square",
      color: "rgb(239,216,29)",
      questions: [
          {number: 1, front: "Explain the function of the following array method:\nmyArray.push('new element');", back: "It adds a new element to the end of the array.\nMultiple elements can be added by separating them with commas.\nThis alters the original array and does not return anything.", article1Name: "MDN Web Docs- push()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push", article2Name: "W3 Schools- push()", article2URL: "https://www.w3schools.com/jsref/jsref_push.asp"},
          {number: 2, front: "Explain the function of the following array method:\nmyArray.splice(2, 1, 'new element');", back: "It removes and adds elements.\nThe first parameter is the index to start removing from.\nThe second parameter is the amount of entries to remove.\nThe third parameter is the element(s) you wish to insert.", article1Name: "MDN Web Docs- splice()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice", article2Name: "W3 Schools- splice()", article2URL: "https://www.w3schools.com/jsref/jsref_splice.asp"},
          {number: 3, front: "Explain the function of the following array method:\nmyArray.unshift('new element');", back: "It adds a new element to the beginning of the array.\nIt alters the original array and does not return anything.", article1Name: "MDN Web Docs- unshift()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift", article2Name: "W3 Schools- unshift()", article2URL: "https://www.w3schools.com/jsref/jsref_unshift.asp"},
          {number: 4, front: "Explain the function of the following array method:\nmyArray.pop()", back: "It removes and returns the last element in the array.\nIt takes no arguments.", article1Name: "MDN Web Docs- pop()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/pop", article2Name: "W3 Schools- pop()", article2URL: "https://www.w3schools.com/jsref/jsref_pop.asp"},
          {number: 5, front: "Explain the function of the following array method:\nmyArray.shift();", back: "It removes and returns the element at index 0 in the array\nIt takes no arguments.", article1Name: "MDN Web Docs- shift()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/shift", article2Name: "W3 Schools- shift()", article2URL: "https://www.w3schools.com/jsref/jsref_shift.asp"},
          {number: 6, front: "Explain the function of the following array method:\nmyArray.join();", back: "It returns a string containing all elements in the array.\nIt can take a character as an argument that will be inserted between each element.", article1Name: "MDN Web Docs- join()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/join", article2Name: "Scotch.io- join()", article2URL: "https://scotch.io/glossary/javascript/array-join-method"},
          {number: 7, front: "Explain the function of the following array method:\nArray.from(arrayLikeObject);", back: "It returns an array from an 'array like' iterable element.\nIt works on things like HTML collections, strings and node lists.", article1Name: "MDN Web Docs- Array.from()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from", article2Name: "5 Handy Applications of Array.from()", article2URL: "https://dmitripavlutin.com/javascript-array-from-applications/"},
          {number: 8, front: "Explain the function of the following array method:\nmyArray.sort();", back: "It sorts the elements in the array in alphabetical order.", article1Name: "MDN Web Docs- sort()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/sort", article2Name: "JS Array Sort- How to Use JS Sort Methods", article2URL: "https://www.freecodecamp.org/news/javascript-array-sort-tutorial-how-to-use-js-sort-methods-with-code-examples/"},
          {number: 9, front: "Explain the function of the following array method:\nmyArray.toString();", back: "It returns the array as a string.\nIt separates each element with a comma.", article1Name: "MDN Web Docs- toString()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toString", article2Name: "Programiz- JavaScript Array toString()", article2URL: "https://www.programiz.com/javascript/library/array/tostring"},
          {number: 10, front: "Explain the function of the following array method:\nmyArray.length();", back: "It returns the length of the array.", article1Name: "MDN Web Docs- length()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/length", article2Name: "JavaScript Array Length Explained", article2URL: "https://www.freecodecamp.org/news/javascript-array-length/"},
          {number: 11, front: "Explain the function of the following array method:\nmyArray.reverse();", back: "It returns the original array in reverse order.\nIt mutates the original array.", article1Name: "MDN Web Docs- reverse()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse", article2Name: "How to Reverse Arrays Without Using .reverse()", article2URL: "https://josephcardillo.medium.com/how-to-reverse-arrays-in-javascript-without-using-reverse-ae995904efbe"},
          {number: 12, front: "Explain the function of the following array method:\nmyArray.indexOf('element');", back: "It returns the index of the element passed as an argument.\nIf the passed element does not exist, the method will return '-1'.", article1Name: "MDN Web Docs- indexOf()", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf", article2Name: "How to Get the Index of an Item in a JS Array", article2URL: "https://flaviocopes.com/how-to-get-index-item-array-javascript/"},  
          {number: 13, front: "Explain the function of the following array method:\nmyArray.includes('element');", back: "It returns true or false depending on whether the array contains the passed element.\nIt takes an optional 'from' index where it will start searching from.", article1Name: "MDN Web Docs- includes()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes", article2Name: "Checking if an Array Contains a Value in JS", article2URL: "https://dmitripavlutin.com/javascript-array-contains-value/"},
          {number: 14, front: "Explain the function of the following array method:\nArray.isArray('element');", back: "It returns true or false depending on whether the passed element is an array.", article1Name: "MDN Web Docs- Array.isArray()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray", article2Name: "Better Array Check with Array.isArray()", article2URL: "https://medium.com/dailyjs/better-array-check-with-array-isarray-dae0283263be"},  
          {number: 15, front: "Explain the function of the following code:\nlet thirdArray = firstArray.concat(secondArray);", back: "It returns a third array containing all of the elements from the first and second arrays.", article1Name: "MDN Web Docs- concat()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat", article2Name: "Two Ways to Merge Arrays in JavaScript", article2URL: "https://www.samanthaming.com/tidbits/49-2-ways-to-merge-arrays/"},  
          {number: 16, front: "Explain the function of the following code:\nlet newArray = [1, 6 ...oldArray, 9, 8];", back: "It returns a new array with all of the elements from the old array in the middle. This adds the elements from the array; it does not add a nested array.", article1Name: "MDN Web Docs- Spread Operator", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/Spread_syntax", article2Name: "ES6 Tutorials: Spread Operator with Fun", article2URL: "https://www.codingame.com/playgrounds/7998/es6-tutorials-spread-operator-with-fun"},
          {number: 17, front: "Explain the function of the following array method:\nmyArray.findIndex(callbackFunc)", back: "It iterates over every element in the array and executes the callback function.\nIt will return the index of the first element that satisfies the function criteria.", article1Name: "MDN Web Docs- findIndex()", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex", article2Name: "Tech on the Net: Array findIndex() Method", article2URL: "https://www.techonthenet.com/js/array_findindex.php"}  
        ],
    },
    {
        setName: "PHP Variables and Strings",
        setNumber: 2,
        tech: "PHP",
        icon: "fab fa-php",
        color: "rgb(115,119,173)",
        questions: [
            {number: 1, front: "What extension is used for PHP files?", back: "fileName.php", article1Name: "What is a PHP File?", article1URL: "https://www.lifewire.com/php-file-4138559#:~:text=A%20file%20with%20the%20.,seen%20in%20the%20web%20browser.", article2Name: "W3 Schools- PHP Introduction", article2URL: "https://www.w3schools.com/php/php_intro.asp"},
            {number: 2, front: "True or false- You can include PHP anywhere in an HTML file?", back: "True, although some developers consider this bad practice because of the theory of 'separation of concerns'.", article1Name: "PHP in HTML", article1URL: "https://www.ntchosting.com/encyclopedia/scripting-and-programming/php/php-in/", article2Name: "Is it Bad Pracice to Include HTML and PHP in the Same File?", article2URL: "https://www.quora.com/Is-it-bad-practice-to-include-HTML-and-PHP-in-the-same-file"},
            {number: 3, front: "How should you format a single line comment?", back: "// or #", article1Name: "PHP.net- Comments", article1URL: "https://www.php.net/manual/en/language.basic-syntax.comments.php", article2Name: "Putting Comments in code: The Good, The Bad and The Ugly", article2URL: "https://www.freecodecamp.org/news/code-comments-the-good-the-bad-and-the-ugly-be9cc65fbf83/"},
            {number: 4, front: "How should you format a multi-line comment?", back: "//", article1Name: "W3 Schools- PHP Comments", article1URL: "https://www.w3schools.com/php/php_comments.asp", article2Name: "How to Comment Your Code Like a Pro", article2URL: "https://www.elegantthemes.com/blog/wordpress/how-to-comment-your-code-like-a-pro-best-practices-and-good-habits"},
            {number: 5, front: "How should you concatenate?", back: "Use a full stop between clauses.\nFor example:\necho 'My name is ' . $nameVar ", article1Name: "PHP.net- String Operators", article1URL: "https://www.php.net/manual/en/language.operators.string.php", article2Name: "PHPPot- PHP String Concatenation", article2URL: "https://phppot.com/php/php-string-concatenation/"},
            {number: 6, front: "How can you output text or a variable to the console?", back: "'echo 'Text here' or 'print('Text here')'", article1Name: "PHP.net- echo", article1URL: "https://www.php.net/manual/en/function.echo.php", article2Name: "W3 Schools- Echo/Print", article2URL: "https://www.w3schools.com/php/php_echo_print.asp"},
            {number: 7, front: "How can you print an array to the console?", back: "print_r($arrayName)", article1Name: "Echo or Print an Array in PHP", article1URL: "https://www.delftstack.com/howto/php/how-to-echo-or-print-an-array-in-php/", article2Name: "PHP Debugging", article2URL: "https://www.codebyamir.com/blog/php-debugging-varexport-vardump-printr"},
            {number: 8, front: "What must a variable always start with?", back: "The dollar sign ($).", article1Name: "W3 Schools- Variables", article1URL: "https://www.w3schools.com/php/php_variables.asp", article2Name: "PHPTPoint- Variables", article2URL: "https://www.phptpoint.com/php-variables/"},
            {number: 9, front: "How can you use a global variable inside a function?", back: "You must bring them inside the function by using the 'global' keyword and then the variable names you need.\nFor example:\nglobal $varOne, $varTwo;", article1Name: "PHP.net- Scope", article1URL: "https://www.php.net/manual/en/language.variables.scope.php", article2Name: "W3 Schools- Scope", article2URL: "https://www.w3schools.com/php/php_variables_scope.asp"},
            {number: 10, front: "Explain the following variable assignment.\n$new_var = $old_var;", back: "This is assigned by value, meaning that $new_var holds a copy of $old_var. $new_var can be changed without affecting $old_var.", article1Name: "Pass By Value vs Pass By Reference", article1URL: "https://www.educative.io/edpresso/pass-by-value-vs-pass-by-reference", article2Name: "Video: Pass By Value vs Pass By Reference", article2URL: "https://www.youtube.com/watch?v=hNR6fsksEu8&vl=en&ab_channel=TheCodingTrain"},
            {number: 11, front: "Explain the following variable assignment.\n$new_var &= $old_var;", back: "This is assigned by reference. This means that both $new_var and $old_var point to the same location in memory. Changing one will change the other.", article1Name: "PHP.net- Assigning by Reference", article1URL: "https://www.php.net/manual/en/language.operators.assignment.php", article2Name: "PHP References: How They Work and When to Use Them", article2URL: "https://www.elated.com/php-references/"},            
            {number: 12, front: "True or false- Convention states that PHP variables should be named using PascalCase?", back: "False. PHP variables are typically named using snake_case.", article1Name: "Basics of Naming Conventions in PHP", article1URL: "https://www.codementor.io/@veenitchauhan/basics-of-naming-conventions-for-php-developers-eliexmew6", article2Name: "Video: Naming Variables, Functions and Classes in PHP", article2URL: "https://www.youtube.com/watch?v=0e-AWOIipxs&ab_channel=DaveHollingworth"},
            {number: 13, front: "True or false- In PHP, you cannot include variables within a string?", back: "False. This can be done using the following syntax:\n'Hello my name is $nameVar'", article1Name: "PHP Variable Interpolation", article1URL: "https://phppot.com/php/variable-interpolation-in-php/", article2Name: "Mixing a PHP Variable with a String Literal", article2URL: "https://stackoverflow.com/questions/5368890/mixing-a-php-variable-with-a-string-literal"}
        ],
    },
    {
        setName: "CSS Animations",
        setNumber: 3,
        tech: "CSS",
        icon: "fab fa-css3-alt",
        color: "rgb(1,108,180)",
        questions: [
            {number: 1, front: "True or false- 'transition-duration' can only take values in ms?", back: "False. It accepts seconds or milliseconds, as long as the units are defined.", article1Name: "MDN Web Docs- transition-duration", article1URL: "https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration", article2Name: "CSS Transitions and Transforms for Beginners", article2URL: "https://thoughtbot.com/blog/transitions-and-transforms"},
            {number: 2, front: "True or false- You can only specify one 'transition-property'?", back: "False. It can take multiple, separated by a comma, or it can take 'all', 'none', 'inherit' or 'initial'.", article1Name: "MDN Web Docs- transition-property", article1URL: "https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property", article2Name: "CSS Transitions Explained", article2URL: "https://www.freecodecamp.org/news/css-transitions-explained-d67ab9a02049/"},
            {number: 3, front: "True or false- 'transition-delay' specifies how long you have to wait before the transition can be triggered again?", back: "False. It specifies how long after the trigger the transition starts.", article1Name: "MDN Web Docs- transition-delay", article1URL: "https://developer.mozilla.org/en-us/docs/Web/CSS/transition-delay", article2Name: "CSS Tricks: Transition Delay Delays", article2URL: "https://css-tricks.com/transition-delay-delays/"},
            {number: 4, front: "What five values can 'transition-timing-function' take?", back: "ease\nease-in\nease-out\nease-in-out\nlinear", article1Name: "MDN Web Docs- transition-timing-function", article1URL: "https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function", article2Name: "Understanding the CSS3 transition-timing-function Property", article2URL: "https://www.smashingmagazine.com/2014/04/understanding-css-timing-functions/"},
            {number: 5, front: "The 'transition' property is shorthand. Which order should you specify values in it?", back: "property -> duration -> timing-function -> delay", article1Name: "MDN Web Docs- transition", article1URL: "https://developer.mozilla.org/en-US/docs/Web/CSS/transition", article2Name: "CSS Transitions Explained", article2URL: "https://www.freecodecamp.org/news/css-transitions-explained-d67ab9a02049/#:~:text=The%20transition%20property%20is%20a,%2Dfunction%20%2C%20transition%2Ddelay%20.&text=It%20is%20required%20in%20the,the%20duration%20of%20the%20transition."},
            {number: 6, front: "True or false- You can combine multiple transition rules using the shorthand 'transition' property.", back: "True. Separate the first set of transition instructions from the next using a comma.", article1Name: "Course: Transition Shorthand", article1URL: "https://scrimba.com/learn/cssanimations/transition-shorthand-cBzk3KCz", article2Name: "CSS Transitions", article2URL: "http://css3.bradshawenterprises.com/transitions/"},
            {number: 7, front: "What's the difference between 'transition' and 'transform'?", back: "Transform changes the look or location of an element.\nTranssition smooths the journey between the two states.", article1Name: "MDN Web Docs- transform", article1URL: "https://developer.mozilla.org/en-US/docs/Web/CSS/transform", article2Name: "Transitions and Transforms for Beginners", article2URL: "https://thoughtbot.com/blog/transitions-and-transforms"}
        ],
    },
    {
        setName: "React Basics",
        setNumber: 4,
        tech: "React",
        icon: "fab fa-react",
        color: "rgb(97,219,251)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "HTML",
        setNumber: 5,
        tech: "HTML",
        icon: "fab fa-html5",
        color: "rgb(221,75,37)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "Python",
        setNumber: 6,
        tech: "Python",
        icon: "fab fa-python",
        color: "rgb(54,108,156)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "JavaScript Variables",
        setNumber: 7,
        tech: "JavaScript",
        icon: "fab fa-js-square",
        color: "rgb(239,216,29)",
        questions: [
            {number: 1, front: "True or false- Variables cannot start with a number?", back: "True. They can only start with a letter, $ or _", article1Name: "W3 Schools- Variables", article1URL: "https://www.w3schools.com/js/js_variables.asp", article2Name: "JavaScript Style Guide", article2URL: "https://www.w3schools.com/js/js_conventions.asp"},
            {number: 2, front: "True or false- You can declare a variable and not assign it a value.", back: "True. This leaves the value as 'undefined'. You can declare a variable with the following syntax:\nlet varName;", article1Name: "JavaScript Variables", article1URL: "https://www.tutorialsteacher.com/javascript/javascript-variable#:~:text=JavaScript%20uses%20reserved%20keyword%20var,it%20or%20before%20using%20it.&text=In%20the%20above%20example%2C%20we,%3A%20one%2C%20two%20and%20three.", article2Name: "JavaScript Intro to Variable Assignment", article2URL: "https://learn.co/lessons/javascript-intro-to-variable-assignment-and-declaration"},
            {number: 3, front: "What is the difference between 'var', 'let' and 'const'?", back: "'var' is pre-ES6 terminology. This declares any variable.\n'let' assigns a variable that can be changed.\n'const' defines a variable that cannot be changed.", article1Name: "Var, Let and Const- What's the Difference?", article1URL: "https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/", article2Name: "Var vs. Let vs. Const in JavaScript", article2URL: "https://ui.dev/var-let-const/"},
            {number: 4, front: "What is a 'global variable'?", back: "A variable that is declared outside of a function. It can be used in any function within your page.", article1Name: "W3 Schools- JavaScript Scope", article1URL: "https://www.w3schools.com/js/js_scope.asp", article2Name: "Global Variables in JavaScript Explained", article2URL: "https://www.freecodecamp.org/news/global-variables-in-javascript-explained/"},
            {number: 5, front: "What is a 'local variable'?", back: "A variable that is declared inside of a function. It can only be used within that function.", article1Name: "Global and Local Variables in JavaScript", article1URL: "https://www.geeksforgeeks.org/global-and-local-variables-in-javascript/", article2Name: "Understanding Javascript Scope", article2URL: "https://scotch.io/tutorials/understanding-scope-in-javascript"},
            {number: 6, front: "What are the seven data types in JavaScript?", back: "undefined, null, boolean, string, number, object, array.", article1Name: "W3 Schools- Data Types", article1URL: "https://www.w3schools.com/js/js_datatypes.asp", article2Name: "JavaScript Data Types", article2URL: "https://www.tutorialrepublic.com/javascript-tutorial/javascript-data-types.php"},
            {number: 7, front: "What is an 'undefined' variable?", back: "Where a variable is declared but has not been assigned a value yet.", article1Name: "MDN Web Docs- undefined", article1URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined", article2Name: "7 Tips to Handle undefined in JavaScript", article2URL: "https://dmitripavlutin.com/7-tips-to-handle-undefined-in-javascript/"},
            {number: 8, front: "What is a 'null' variable?", back: "When a variable is assigned 'null', it is to be intentionally left empty.", article1Name: "JavaScript: Null vs. Undefined", article1URL: "https://codeburst.io/javascript-null-vs-undefined-20f955215a2", article2Name: "MDN Web Docs- null", article2URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/null"},
            {number: 9, front: "What is a 'boolean'?", back: "A boolean is either true or false (with no quotation marks).", article1Name: "MDN Web Docs- Boolean", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Boolean", article2Name: "JavaScript Boolean vs boolean", article2URL: "https://www.javascripttutorial.net/javascript-boolean/"},
            {number: 10, front: "What is a 'string'?", back: "A series of characters encased in quotation marks.", article1Name: "MDN Web Docs- String", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String", article2Name: "W3 Schools- String", article2URL: "https://www.w3schools.com/jsref/jsref_obj_string.asp"},
            {number: 11, front: "What is a 'number'?", back: "Decimals or integers. There is no distinction between the two, like in some languages.", article1Name: "MDN Web Docs- Number", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Number", article2Name: "W3 Schools- Numbers", article2URL: "https://www.w3schools.com/js/js_numbers.asp"},
            {number: 12, front: "What is an 'object'?", back: "A collection of information arranged in key:value pairs, within curly brackets {}.", article1Name: "MDN Web Docs- Object", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object", article2Name: "JavaScript.info- Object", article2URL: "https://javascript.info/object"},
            {number: 13, front: "What is an 'array'?", back: "A collection of data contained within square brackets []", article1Name: "MDN Web Docs- Array", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array", article2Name: "JavaScript Arrays- Tips, Tricks and Examples", article2URL: "https://www.codingame.com/playgrounds/6181/javascript-arrays---tips-tricks-and-examples"},
            {number: 14, front: "How can you check what data type your variable is?", back: "typeof varName", article1Name: "MDN Web Docs", article1URL: "https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/typeof", article2Name: "Understanding Type Checking in JavaScript", article2URL: "https://blog.logrocket.com/javascript-typeof-2511d53a1a62/"},
            {number: 15, front: "What are falsy values?", back: "A value that is considered false when encountered in a Boolean context.", article1Name: "MDN Web Docs- Falsy", article1URL: "https://developer.mozilla.org/en-US/docs/Glossary/Falsy", article2Name: "Truthy and Falsy: When All is not Equal in JS", article2URL: "https://www.sitepoint.com/javascript-truthy-falsy/"},
            {number: 16, front: "There are 6 main falsy values in JavaScript. What are they?", back: "undefined, null, NaN, 0, ' ' (empty string), and false", article1Name: "Video: Truthy and Falsey", article1URL: "https://www.youtube.com/watch?v=6hESXoxDtgo&ab_channel=SamBennett", article2Name: "MDN Web Docs- Truthy", article2URL: "https://developer.mozilla.org/en-US/docs/Glossary/Truthy"},
            {number: 17, front: "JavaScript is a loosely typed language. What does this mean?", back: "It means that you do not need to specify the datatype of your variables.", article1Name: "JavaScript is a Loosely Typed Language", article1URL: "https://medium.com/@xiaoyunyang/javascript-is-a-loosely-typed-language-meaning-you-dont-have-to-specify-what-type-of-information-137408d54fc7", article2Name: "An Introduction to Programming Type Systems", article2URL: "https://www.smashingmagazine.com/2013/04/introduction-to-programming-type-systems/"},
            {number: 18, front: "What is a 'primitive data type'?", back: "A data type that cannot be broken down into a more simple data type.", article1Name: "A Quick Tour of JavaScript Primitives", article1URL: "https://milkjar.medium.com/a-quick-tour-of-javascript-primitives-894eceee31c2", article2Name: "Understanding JS Primitives", article2URL: "https://codeburst.io/understanding-js-primitives-fafe16468c16"},
            {number: 19, front: "In JavaScript, what are the primitive data types?", back: "numbers, strings, booleans, undefined and null.", article1Name: "The Secret Life of JavaScript Primitives", article1URL: "https://javascriptweblog.wordpress.com/2010/09/27/the-secret-life-of-javascript-primitives/", article2Name: "JavaScript Primitives Guide", article2URL: "https://www.vojtechruzicka.com/javascript-primitives/"},
            {number: 20, front: "True or false- primitive data types are assigned by value, not reference?", back: "True. This means that they are considered to 'contain' the primitive value.", article1Name: "Explaining Value vs. Reference in JS", article1URL: "https://codeburst.io/explaining-value-vs-reference-in-javascript-647a975e12a0", article2Name: "JavaScript by Reference vs. By Value", article2URL: "https://stackoverflow.com/questions/6605640/javascript-by-reference-vs-by-value"},
            {number: 21, front: "True or false- non-primitive data types are assigned by value, not reference?", back: "False. Non-primitives are created in a space in memory. The variable points to that location and doesn't actually 'contain' the value.", article1Name: "Value vs. Reference", article1URL: "https://www.educative.io/courses/step-up-your-js-a-comprehensive-guide-to-intermediate-javascript/7nAZrnYW9rG", article2Name: "Video: Reference vs Value in JavaScript", article2URL: "https://www.youtube.com/watch?v=-hBJz2PPIVE&ab_channel=WebDevSimplified"}
        ],
      },
    {
        setName: "Java",
        setNumber: 8,
        tech: "Java",
        icon: "fab fa-java",
        color: "rgb(255,0,2)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "C#",
        setNumber: 9,
        tech: "C#",
        icon: "",
        color: "rgb(160,118,219)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "Node.js",
        setNumber: 10,
        tech: "Node",
        icon: "fab fa-node-js",
        color: "rgb(127,199,40)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "Terminal",
        setNumber: 11,
        tech: "Terminal",
        icon: "fas fa-terminal",
        color: "rgb(255,255,255)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
    {
        setName: "jQuery",
        setNumber: 12,
        tech: "JavaScript",
        icon: "fab fa-js-square",
        color: "rgb(239,216,29)",
        questions: [
            {number: 1, front: "What's the JS Mr. Wolf?", back: "Three pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 2, front: "What's the frontend Mrs. Wolf?", back: "Four pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
            {number: 3, front: "What's the pooface Ms. Wolf?", back: "Five pm!", article1Name: "Article Name", article1URL: "https://kateeliza.co.uk", article2Name: "Article2 Name", article2URL: "http://google.com"},
        ],
    },
  ];

  //Add in hints
  /* Empty Datasets */
  /* 
              {number: 2, front: "", back: "", article1Name: "", article1URL: "", article2Name: "", article2URL: ""},
            {number: 3, front: "", back: "", article1Name: "", article1URL: "", article2Name: "", article2URL: ""},
            {number: 4, front: "", back: "", article1Name: "", article1URL: "", article2Name: "", article2URL: ""},
            {number: 5, front: "", back: "", article1Name: "", article1URL: "", article2Name: "", article2URL: ""},*/